apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: techinsight-api=lifegoeson34/techinsight-api
    argocd-image-updater.argoproj.io/techinsight-api.update-strategy: semver
    argocd-image-updater.argoproj.io/techinsight-api.allow-tags: regexp:^v?[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/TechInsighApiV2
    path: .
    targetRevision: HEAD 

  destination:
    server: https://kubernetes.default.svc
    namespace: TechInsight

  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
