# Certificate cho api.techinsightsworld.com và admin.techinsightsworld.com
# Apply: kubectl apply -f k8s/certificate-techinsight-api.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techinsight-api-tls
  namespace: techinsight
spec:
  secretName: techinsight-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - api.techinsightsworld.com
    - admin.techinsightsworld.com
    - minio.techinsightsworld.com
    - kibana.techinsightsworld.com
    - redpanda.techinsightsworld.com
  usages:
    - digital signature
    - key encipherment
