apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lingocast-tls
  namespace: lingocast
spec:
  secretName: lingocast-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - lingocast-core.modami.cloud
