# Service accounts for Vault Kubernetes auth. Each workload uses its SA to authenticate to Vault.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-lingocast-core-service
  namespace: lingocast
  labels:
    app: be-lingocast-core-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-lingocast-job-scheduler
  namespace: lingocast
  labels:
    app: be-lingocast-job-scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voice-analyze-and-summarizer-asr
  namespace: lingocast
  labels:
    app: voice-analyze-and-summarizer-asr
