{{- with secret "secret/data/modami/centrifugo" }}
{
  "port": 8000,
  "grpc_api": true,
  "grpc_api_port": 10000,
  "health": true,
  "log_level": "info",
  "granular_proxy_mode": true,
  "token_hmac_secret_key": "{{ .Data.data.token_hmac_secret_key }}",
  "api_key": "{{ .Data.data.api_key }}",
  "admin": true,
  "admin_password": "{{ .Data.data.admin_password }}",
  "admin_secret": "{{ .Data.data.admin_secret }}",
  "proxies": [
    {
      "name": "noti-subscribe",
      "endpoint": "http://be-modami-noti-service-ws-gateway.modami.svc.cluster.local:7072/centrifugo/subscribe",
      "timeout": "3s"
    },
    {
      "name": "noti-publish",
      "endpoint": "http://be-modami-noti-service-ws-gateway.modami.svc.cluster.local:7072/centrifugo/publish",
      "timeout": "3s"
    },
    {
      "name": "chat-subscribe",
      "endpoint": "http://localhost:CHAT_GATEWAY_PORT/centrifugo/subscribe",
      "timeout": "3s"
    },
    {
      "name": "chat-publish",
      "endpoint": "http://localhost:CHAT_GATEWAY_PORT/centrifugo/publish",
      "timeout": "3s"
    }
  ],
  "namespaces": [
    {
      "name": "noti",
      "presence": false,
      "history_size": 20,
      "history_ttl": "168h",
      "force_recovery": true,
      "proxy_subscribe": true,
      "subscribe_proxy_name": "noti-subscribe",
      "proxy_publish": true,
      "publish_proxy_name": "noti-publish"
    },
    {
      "name": "chat",
      "presence": true,
      "join_leave": true,
      "history_size": 100,
      "history_ttl": "24h",
      "force_recovery": true,
      "proxy_subscribe": true,
      "subscribe_proxy_name": "chat-subscribe",
      "proxy_publish": true,
      "publish_proxy_name": "chat-publish"
    }
  ]
}
{{- end }}
