{{- with secret "secret/data/modami/be-modami-chat-service" }}
app:
  name: "be-modami-chat-service"
  version: "1.0.0"
  environment: "production"
  debug: true
  port: 8090
  host: "0.0.0.0"
  swagger_host: "chat.modami.cloud"
  shutdown_timeout: "30s"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  allow_credentials: true
  allowed_origins:
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:8081"

scylladb:
  hosts:
    - "scylladb.modami.svc.cluster.local"
  keyspace: "chat"
  num_conns: 2
  datacenter: "dc1"
  replication_factor: 1

mongodb:
  uri: "{{ .Data.data.mongodb_uri }}"
  database: "{{ .Data.data.mongodb_database }}"
  timeout: 10s
  max_pool_size: 100
  min_pool_size: 0
  max_idle_time: 900s
  retry_writes: true
  read_concern: "majority"
  write_concern: "majority"
  enable_logging: false

redis:
  host: "redis.techinsight.svc.cluster.local"
  port: 6379
  database: 7
  rate_limit_database: 5
  ttl: 259200s
  pool_size: 100
  pass: "{{ .Data.data.redis_password }}"
  user_name: ""
  write_timeout: 600s
  read_timeout: 600s
  dial_timeout: 600s
  tls_config:
    insecure_skip_verify: true

kafka:
  broker_list: "techinsight-kafka-kafka-bootstrap.techinsight.svc.cluster.local:9092"
  enable: true
  tls_enable: false
  partition: 1
  partitioner: "random"
  sasl_producer_username: ""
  sasl_producer_password: ""
  sasl_consumer_username: ""
  sasl_consumer_password: ""
  consumer_group: "chat-service-group"
  client_id: "chat-service"
  env: "production"

centrifugo:
  api_url: "http://centrifugo.modami.svc.cluster.local:8000/api"
  api_key: "{{ .Data.data.centrifugo_api_key }}"
  hmac_secret: "{{ .Data.data.centrifugo_hmac_secret }}"

observability:
  service_name: "chat-service"
  service_version: "1.0.0"
  environment: "production"
  log_level: "info"
  otlp_endpoint: "otel-collector.techinsight.svc.cluster.local:4317"
  otlp_insecure: true
{{- end }}
