# Service accounts for Vault Kubernetes auth. Each workload uses its SA to authenticate to Vault.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-modami-auth-service
  namespace: modami
  labels:
    app: be-modami-auth-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-modami-user-service
  namespace: modami
  labels:
    app: be-modami-user-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-modami-core-service
  namespace: modami
  labels:
    app: be-modami-core-service
