# ArgoCD Application: Auth Service (gRPC)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techinsight-auth-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: techinsight
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/apps/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: techinsight
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
