# ArgoCD Application: shared resources (namespace, secrets, serviceaccounts, ingress, certs, pdb)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techinsight-base
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: techinsight
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/base/techinsight
  destination:
    server: https://kubernetes.default.svc
    namespace: techinsight
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
# ArgoCD Application: modami shared resources (namespace, secrets, serviceaccounts, ingress, pdb)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modami-base
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: modami
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/base/modami
  destination:
    server: https://kubernetes.default.svc
    namespace: modami
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
# ArgoCD Application: lingocast shared resources (namespace, serviceaccounts, ingress, cert, pdb)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lingocast-base
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: lingocast
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/base/lingocast
  destination:
    server: https://kubernetes.default.svc
    namespace: lingocast
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
