apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-mcp-server
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: internal-mcp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/apps/internal-mcp/mcp-server
    kustomize:
      images:
        - lifegoeson34/mcp-server:latest@sha256:74d0fb54cc15615542af2b711eaa054da44ec28750783275480356369c2fd565
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
