# ArgoCD Application: Backend Worker Service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techinsight-be-worker-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: techinsight
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nguyencaophong/k8s-manifest.git
    targetRevision: HEAD
    path: k8s/apps/techinsight/be-techinsight-worker-service
  destination:
    server: https://kubernetes.default.svc
    namespace: techinsight
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
